### ISSUE TITLE
Unable to reproduce the numbers on pouring

### ISSUE THREAD

**Issue by deepsworld** [hengRUC/VSP#3]
Hello,

Thank you very much for sharing your interesting work. I tried to reproduce the numbers on the pouring dataset using the following config on a machine with 4 GPUs with batch size of 18 per GPU. The paper mentions using a batch size of 128 but since pouring only has 70 train samples, it requires lower batch size. 

Can you please let me know if there is something wrong with the config? 

![image](https://github.com/user-attachments/assets/b4eb74fa-2fdd-44c7-ad00-78fa5bab1b5b)

```yaml
AUGMENTATION:
  BRIGHTNESS: true
  BRIGHTNESS_MAX_DELTA: 0.8
  CONTRAST: true
  CONTRAST_MAX_DELTA: 0.8
  HUE: true
  HUE_MAX_DELTA: 0.2
  RANDOM_CROP: true
  RANDOM_FLIP: true
  SATURATION: true
  SATURATION_MAX_DELTA: 0.8
  STRENGTH: 1.0
CHECKPOINT:
  SAVE_INTERVAL: 50
DATA:
  ADDITION_TRAINSET: false
  ANNOTATION: raw
  CONSISTENT_OFFSET: 0.2
  CONTEXT_STRIDE: 1
  FRACTION: 1.0
  FRAME_LABELS: true
  NUM_CONTEXTS: 1
  NUM_WORKERS: 2
  SAMPLE_ALL_STRIDE: 1
  SAMPLING_REGION: 1.5
  SAMPLING_STRATEGY: time_augment
DATASETS:
- pouring
EVAL:
  BATCH_SIZE: 1
  CLASSIFICATION_FRACTIONS:
  - 0.1
  - 0.5
  - 1.0
  FRAMES_PER_BATCH: 1000
  KENDALLS_TAU_DISTANCE: sqeuclidean
  KENDALLS_TAU_STRIDE: 5
  NUM_FRAMES: 120
  RETRIEVAL_KS:
  - 5
  - 10
  - 15
  TASKS:
  - kendalls_tau
  - retrieval
  - classification
  - event_completion
  VAL_INTERVAL: 50
IMAGE_SIZE: 224
LOGDIR: logs_e300/
LOGGING:
  REPORT_INTERVAL: 20
MODEL:
  BASE_MODEL:
    FRAMES_PER_BATCH: 40
    LAYER: 3
    NETWORK: Resnet50_byol
  EMBEDDER_MODEL:
    CAPACITY_SCALAR: 2
    CONV_LAYERS:
    - &id001
      - 256
      - 3
      - 1
    - *id001
    D_FF: 1024
    EMBEDDING_SIZE: 128
    FC_DROPOUT_RATE: 0.1
    FC_LAYERS:
    - &id002
      - 256
      - true
    - *id002
    FLATTEN_METHOD: max_pool
    HIDDEN_SIZE: 256
    NUM_HEADS: 8
    NUM_LAYERS: 3
    USE_BN: true
  EMBEDDER_TYPE: transformer
  L2_NORMALIZE: true
  PROJECTION: true
  PROJECTION_HIDDEN_SIZE: 512
  PROJECTION_SIZE: 128
  TRAIN_BASE: frozen
NUM_GPUS: 1
OPTIMIZER:
  GRAD_CLIP: 10
  LR:
    DECAY_TYPE: cosine
    FINAL_LR: 0.0
    INITIAL_LR: 0.0001
    NUM_WARMUP_STEPS: 1
    WARMUP_LR: 0.0001
  TEMPERATURE: 0.1
  TYPE: AdamOptimizer
  WEIGHT_DECAY: 1.0e-05
PATH_TO_DATASET: pouring
PENNACTION:
- baseball_pitch
- baseball_swing
- bench_press
- bowl
- clean_and_jerk
- golf_swing
- jumping_jacks
- pushup
- pullup
- situp
- squat
- tennis_forehand
- tennis_serve
RNG_SEED: 1
SCL:
  LABEL_VARIENCE: 10.0
  NEGATIVE_TYPE: single_noself
  POSITIVE_TYPE: gauss
  POSITIVE_WINDOW: 5
  SOFTMAX_TEMPERATURE: 0.1
SHARD_ID: 0
SIMILARITY_TYPE: l2
SSL: true
TCC:
  CYCLE_LENGTH: 2
  FRACTION: 1.0
  HUBER_DELTA: 0.1
  LABEL_SMOOTHING: 0.1
  LOSS_TYPE: regression_mse_var
  NORMALIZE_INDICES: true
  SOFTMAX_TEMPERATURE: 0.1
  VARIANCE_LAMBDA: 0.001
TCN:
  POSITIVE_WINDOW: 5
  REG_LAMBDA: 0.002
TRAIN:
  BATCH_SIZE: 18
  MAX_EPOCHS: 300
  NUM_BRIDGE: 5
  NUM_FRAMES: 120
  NUM_SEGMENTS: 5
  OVERLAP_RATE: 0.2
  SIGNAL: self
TRAINING_ALGO: scl
TRAINING_WAY: joint
USE_AMP: true
```
